### ISSUE TITLE
D1Mini Mounting?

### ISSUE THREAD

**Issue by brianhanifin** [mannkind/ESPHomeRoombaComponent#4]
Could you share a photo in the documentation of how you mounted your D1 Mini board? I noticed the original project used a bar ESP12E board to keep the size down. Is your basically stuck on top, and has that caused you any problems (when it tries to go under something)?

**Comment by mannkind** [comment]
The D1 mini is still small enough to fit into the compartment by the wheel. I managed to mess up the top plate of my Roomba in an unrelated incident, but before that you couldn't tell it was _hacked_.

This isn't my photo (I'd have to take apart the Roomba to take a pic), but hopefully this gives you an idea: [d1 mini in compartment](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/optimized/2X/a/a258c7253f8bd3fe76ad9e7aa1202b60bd113d74_2_496x600.jpg)

If that's helpful, I could certainly link to it in the docs.

**Comment by brianhanifin** [comment]
Yes. That would be helpful. I was imagining a much more complicated solution involving a 3D printed case on top and some jury rigged way to stop it from ripping the board off the top. :) Thank you.

**Comment by mannkind** [comment]
Updated the readme. Thanks for the feedback!
