### ISSUE TITLE
Cant wake from sleep

### ISSUE THREAD

**Issue by chmadkk** [mannkind/ESPHomeRoombaComponent#5]
Hi. 

Ive been having a little bit of trouble changing to your sketch rather than the john boiles one. 
Now ive encountered that if i stop the vacuum outside of the dock. It falls asleep. and cant be woken unless i push the button. 

Is this the brcPin thats not defined in your sketch ? Should it be defined in the esphome.yaml ?

**Comment by mannkind** [comment]
Sorry you're having trouble; hopefully this will of _some_ help:

* Getting the Roomba to reliably wakeup seems like magic. _On the dock_ I've yet to have issue, but like you mentioned, I've had trouble after the Roomba stops/falls asleep mid-cycle. None of the work-arounds seemed to actually fix it. I just stopped wasting time trying to figure it out. :/

* The BRC pin is defined, but I can see how it'd be missed. It's currently in the ["template" section](https://github.com/mannkind/ESPHomeRoombaComponent/blob/master/example/roomba.yaml#L12). In the example, it's _4_

**Comment by chmadkk** [comment]
Thank you very much. I got everything running. So its defined as D4 in the template? Then it makes sense when i mount it to D5 according to johnboiles repo 😁

**Comment by chmadkk** [comment]
Like said.
Mines an 561. Use the d2 to the wake pin. I change the 4 to 14 and it worked with the schemqtics from johnboiles

**Comment by mannkind** [comment]
Glad to hear it!
